spring:
  config:
    activate:
      on-profile: dev
    import: "optional:file:.env[.properties]"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

external:
  user-service:
    url: http://localhost:8080/
  pet-service:
    url: http://localhost:8080/
  notification-service:
    url: http://localhost:8083/
  storage-service:
    url: http://localhost:8084/

cloud:
  openfeign:
    client:
      config:
        storage-service:
          enabled: false

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY:}